// <auto-generated />
using ExchangeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExchangeAPI.Data.Migrations
{
    [DbContext(typeof(ExchangeDataContext))]
    partial class ExchangeDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ExchangeAPI.Data.Entities.ExchangeRate", b =>
                {
                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.HasKey("Date", "Base", "Currency");

                    b.HasIndex("Currency");

                    b.HasIndex("Date", "Currency");

                    b.ToTable("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
